let fdr = 'Erhan';
let mdr = 'Ayse';
let br1 = 'Osman';
let br1s = 'Nurullah';
let br2 = 'Numan';
let br2s= 'Ahmet';
let me = 'Cagri';
let mes = 'Fatih';
let br3 = 'Furkan';
let br3s = 'Efe';
let lastname = 'Ozdemir';
let   = ' ';
console.log(fdr+' '+lastname);
console.log(mdr+' '+lastname);
console.log(br1+' '+br1s+' '+lastname);
console.log(br2+' '+br2s+' '+lastname);
console.log(me+' '+mes+' '+lastname);
console.log(br3+' '+br3s+' '+lastname);